export const GET_TASKS = 'RESOURCES/TASKS/GET';

export const GET_TASK_ID = 'RESOURCES/TASKS/GET/ID';

export const ADD_TASK = 'RESOURCES/TASKS/ADD';

export const DELETE_TASK = 'RESOURCES/TASKS/DELETE';

export const EDIT_TASK = 'RESOURCES/TASKS/EDIT';

export const COMPLETE_TASK = 'RESOURCES/TASKS/GET/ID/COMPLETE';

export const ADD_NOTIFICATION = 'RESOURCES/NOTIFICATIONS/ADD';

export const DELETE_NOTIFICATION = 'RESOURCES/NOTIFICATIONS/DELETE';
